name: Deploy Flarum Application Only

on:
  workflow_dispatch:
    inputs:
      vm_ip:
        description: 'VM IP Address'
        required: true
        default: ''
      db_host:
        description: 'Database Host'
        required: true
        default: ''
      db_name:
        description: 'Database Name'
        required: true
        default: 'flarum'
      db_user:
        description: 'Database User'
        required: true
        default: 'flarum'
  push:
    branches: [main]
    paths:
      - 'ansible/**'
      - '.github/workflows/deploy-app-only.yml'

env:
  ANSIBLE_VERSION: 7.0.0

jobs:
  # ========================================
  # 1. DEPLOY APPLICATION
  # ========================================
  deploy-application:
    name: 🚀 Deploy Application
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4

      - name: 🐍 Setup Python for Ansible
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: 📦 Install Ansible
        run: |
          pip install ansible==${{ env.ANSIBLE_VERSION }}
          ansible --version

      - name: 🔑 Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.GCP_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ github.event.inputs.vm_ip || '34.63.202.66' }} >> ~/.ssh/known_hosts

      - name: ⏳ Wait for VM to be ready
        run: |
          timeout 180 bash -c 'until ssh -o ConnectTimeout=5 -o StrictHostKeyChecking=no rocky@${{ github.event.inputs.vm_ip || '34.63.202.66' }} "echo VM is ready"; do sleep 15; done'

      - name: 📝 Create Ansible inventory
        run: |
          cat > inventory.ini << EOF
          [flarum]
          ${{ github.event.inputs.vm_ip || '34.63.202.66' }} ansible_user=rocky ansible_ssh_private_key_file=~/.ssh/id_rsa

          [flarum:vars]
          db_host=${{ github.event.inputs.db_host || '34.63.202.66' }}
          db_name=${{ github.event.inputs.db_name || 'flarum' }}
          db_user=${{ github.event.inputs.db_user || 'flarum' }}
          db_password=${{ secrets.DB_PASSWORD }}
          EOF

      - name: 🎭 Run Ansible Playbook
        run: |
          ansible-playbook -i inventory.ini ansible/playbook.yml \
            -e "db_host=${{ github.event.inputs.db_host || '34.63.202.66' }}" \
            -e "db_name=${{ github.event.inputs.db_name || 'flarum' }}" \
            -e "db_user=${{ github.event.inputs.db_user || 'flarum' }}" \
            -e "db_password=${{ secrets.DB_PASSWORD }}" \
            --timeout=60 \
            --forks=1

      - name: 📤 Get VM IP for verification
        id: terraform-outputs
        run: |
          echo "vm_ip=${{ github.event.inputs.vm_ip || '34.63.202.66' }}" >> $GITHUB_OUTPUT

  # ========================================
  # 2. VERIFICATION
  # ========================================
  verify-deployment:
    name: ✅ Verify Deployment
    runs-on: ubuntu-latest
    needs: deploy-application
    timeout-minutes: 5
    
    steps:
      - name: 🌐 Check Flarum Website
        run: |
          VM_IP="${{ needs.deploy-application.outputs.vm_ip || '34.63.202.66' }}"
          echo "Checking Flarum at http://$VM_IP"
          curl -f -s -o /dev/null "http://$VM_IP" && echo "✅ Flarum is accessible" || echo "❌ Flarum is not accessible"
